### PR TITLE
refactor using new React Hooks API

### PR DESCRIPTION
**Pull request by mohsinulhaq**
https://codesandbox.io/s/zqxv37q7vl

### CODE REVIEW

**Comment by mohsinulhaq** [comment]
@denisborovikov I won't be merging until Hooks are officially out. What do you say?

**Comment by denisborovikov** [comment]
Agree

**Comment by mohsinulhaq** [comment]
hahaha...so sad 😂

**Comment by denisborovikov** [comment]
I've added changes from #8. Need to update ts types as well. Help is appreciated.

- [ ] Update ts types

**Comment by mohsinulhaq** [comment]
let's take this after hooks release, i feel we can make more use of hooks

**Pull request closed without merging**
