### PR TITLE
Remove default imports for types and import react without defaultinterop

### PR DESCRIPTION
**Pull request by Scoutski**
Just made some type changes that will allow this package to work with default typescript setups, thought I'd see if you wanted to make this change. Cheers 

```../node_modules/@types/react/index"' can only be default-imported using the 'esModuleInterop' flag

2 import React from 'react';
         ~~~~~

  ../../node_modules/@types/react/index.d.ts:55:1
    55 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

../../node_modules/react-popper-tooltip/dist/types.d.ts:3:8 - error TS1192: Module '"../node_modules/react-popper/typings/react-popper"' has no default export.

3 import ReactPopper from 'react-popper';```

### CODE REVIEW

**Comment by mohsinulhaq** [comment]
So is this change basically for those who don't use esModuleInterop?

**Comment by Scoutski** [comment]
Yes, that was my thought, by default this setting is off in typescript: https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by mohsinulhaq** [comment]
I'm a bit fuzzy on the configuration options, there was a PR which did a similar change in the source files: https://github.com/mohsinulhaq/react-popper-tooltip/pull/39/files
Do you think the `import * as React` syntax should be used in source for people who don't use esModuleInterop? Or just the typings file.

**Comment by Scoutski** [comment]
Yep, very similar to that PR 👍 

Because esModuleInterop is false by default in typescript config, it means a user needs to potentially modify their config to use the module. By making this change, the package should work regardless of their config setup. I think it should probably be used in source as well if possible ✅ but the change in the types was enough to resolve it for me without having to change the config.

**Comment by mohsinulhaq** [comment]
I have made some upgrades.
Can you update this PR with only the required changes?
We can merge after that.
Also, can you post your tsconfig.json here?
Thanks.

**Comment by Scoutski** [comment]
Yep, sure, I'm sorry about the delay, I will get this done soon :)

**Comment by mohsinulhaq** [comment]
Closing this. I would suggest turning `esModuleInterop` for projects.

**Pull request closed without merging**
