### PR TITLE
fix ts issues

### PR DESCRIPTION
**Pull request by elie222**
Was having Typescript issues with this package. This change fixed it for me.

### CODE REVIEW

**Comment by mohsinulhaq** [comment]
did it work?

**Comment by elie222** [comment]
I will give it a try soon. Thanks.

But is this the best solution in any case? Having to assume somebody has
this setting turned on to use this package?

I am using a lot of ts packages and this is the first one giving me this
issue.

If it is a requirement we should add it to the README.

But otherwise loving this package. Has solved me a tonne of headaches
today. Thank you

**Comment by mohsinulhaq** [comment]
understood, it's not really a requirement, but a convenience. The feature was added in TS 1.8, so a lot of devs are not using this option yet. I will merge this PR. But just for confirmation, do tell me if this is a `esModuleInterop` issue or not.

**Comment by elie222** [comment]
Hey,

So I tried just now. I can't actually tell with my project.

I added: `"esModuleInterop": true`.

And now I'm seeing a lot of errors across my app.

For example:

```ts
import * as format from 'date-fns/format'
```

To fix I can do this:

```ts
import format from 'date-fns/format'
```

But then I have 100 other errors across the project.

So yes, I assume that if my project was using `esModuleInterop` this package would be working.

**Comment by mohsinulhaq** [comment]
yeah, got it...merging...thanks!

**Comment by mohsinulhaq** [comment]
hi, before releasing, I would like to know what exactly was the error that you were getting? I would add that to the changelog.

**Comment by mohsinulhaq** [comment]
I have just tried a CRA project with esModuleInterop turned off, the build is still passing for me.

**Comment by elie222** [comment]
Strange. My project is cra ts. But pre 2.0. I will let you know the exact
error soon

**Comment by elie222** [comment]
This is the TS error:

> project/node_modules/react-popper-tooltip/dist/TooltipTrigger.d.ts
(1,8): Module '"project/node_modules/@types/react/index"' has no default export.

**Comment by mohsinulhaq** [comment]
does your project work fine if you enable `allowSyntheticDefaultImports`?

**Comment by elie222** [comment]
Will have to check later. This is my setup though:

https://github.com/wmonk/create-react-app-typescript

And this is the only package I've had to fork to get it working having made use of many TS packages.

**Pull request merged**
