### PR TITLE
Refactor show/hide/toggle methods

### PR DESCRIPTION
**Pull request by denisborovikov**
I refactored `showTooltip`/ `hideTooltip`/`toggleTooltip` methods and removed their scheduled versions. The updated ones can do the same. They accept a number as an argument. If the argument is undefined, `delayShow`/`delayHide` props used as defaults. 

You can pass zero to instantly show/hide the tooltip.

### CODE REVIEW

**Comment by denisborovikov** [comment]
Probably I have to replace `hideTooltip()` with `hideTooltip(0)`

[Here](https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/Tooltip.js#L43) and [here](https://github.com/mohsinulhaq/react-popper-tooltip/blob/master/src/Tooltip.js#L82)

**Comment by denisborovikov** [comment]
After discussion - the lib should respect delay props in all cases.

**Comment by mohsinulhaq** [comment]
can u prefix those methods with underscore? indicating that they are private

**Comment by denisborovikov** [comment]
Done

**Pull request merged**
