### PR TITLE
added support for tooltipDelayShown to get feedback before delayHide is finished

### PR DESCRIPTION
**Pull request by Utzel-Butzel**
This could be useful to trigger a hide animation when leaving the tooltip and having the delay still for a moment so the animation can finish.

### CODE REVIEW

**Comment by mohsinulhaq** [comment]
Instead of the lib telling you when the internal state has changed, why don't you use the tooltip in controlled mode by passing `tooltipShown` and `onVisibilityChange`? That way you have all the control and info about the states.

**Comment by mohsinulhaq** [comment]
Closing this as fixed. Please re-open if still unsolved.

**Comment by Utzel-Butzel** [comment]
@mohsinulhaq This would also mean that each time we would have to implement the `handleClickOutside`, etc.?
Btw. thanks a lot for the great library!

**Comment by mohsinulhaq** [comment]
@Utzel-Butzel no, not at all, that would be all handled by the lib. You would just handle the open/closed state management.

**Pull request closed without merging**
