### PR TITLE
Revert isMouseOutside changes in favor of mouseleave event listener

### LINKED ISSUE #122: Scrolling causes overflowing issues
**Describe the bug**

When tooltips are placed inside a scrolling area, hovering above them and scrolling produces weird results, namely tooltips remaining open and outside the scrolling area.

**To Reproduce**

[Here is a CodeSandbox with an MRE](https://codesandbox.io/s/damp-butterfly-q7x8n).

**Expected behavior**

When scrolling, tooltips should be closed or at least be hidden when "overflowing" the scrolling area.

**Screenshots**

Example of result

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge (Chromium)
 - Version: 89

Please let me know if I can be of further assistance (more details) and my apologies if this issue has a known workaround, I could not find one.

### PR DESCRIPTION
**Pull request by denisborovikov**
The PR is an attempt to fix some edge-case bugs introduced after replacing mouseleave event listener with custom mouse outside position calculations.

Some thoughts are in discussion #126 

The final fix doesn't change the layout of the tooltip in order to avoid breaking changes.

1. `mouseleave` listener reverted, `isMouseOutside` removed
2. New attribute added to the tooltip container, "data-popper-interactive" to display if the tooltip is interactive mode.
2. In CSS `data-popper-interactive="true"` is used to set `pointer-events: none` to the tooltip
3. `pointer-events: none` applied by default to the arrow element
4. Fix missing dependency called clearTimeout on every render rather than on unmount, should fix #122

### CODE REVIEW

**Comment by denisborovikov** [comment]
@czabaj @mohsinulhaq  please take a look, I'll update tests and readme later. I also think we should add an idea from #126 as an example to our examples section.

**Comment by denisborovikov** [comment]
@czabaj I'm really sorry about removing a huge chunk of code you have written.

**Comment by czabaj** [comment]
@denisborovikov well, nobody likes bugs anyway - I'm open to the more bulletproof solution.

**Review by mohsinulhaq — APPROVED** [review]
Looks good to me. 
And because of the `pointer-events: none`, we don't even need to revert back to [0, 7] offset anymore.

**Comment by denisborovikov** [comment]
I've updated the READMe and add a new attribute description. I think we can release this as non-breaking.

**Comment by yomansk8** [comment]
Hi @denisborovikov ! 
Thanks for the quick fix on this 🙏  Do you know when the next release including this fix will be available please ?

**Comment by mohsinulhaq** [comment]
@yomansk8 please check out `v4.2.0`

**Pull request merged**
